kind: pipeline
type: kubernetes
name: drone-pipeline

trigger:
  event:
  - push
  - pull_request
  branches:
  - main
  - dev

steps:
- name: Test Build
  image: golang:1.17
  environment:
    GH_USER:
      from_secret: gh_user
    GH_PAT:
      from_secret: gh_pat
  commands:
  - echo "machine github.com login $GH_USER password $GH_PAT" > ~/.netrc
  - export GOPRIVATE="addysnip.dev"
  - go test
  - make build
- name: Build and Push Image
  image: plugins/gcr
  settings:
    repo: addysnip/emailer
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    json_key:
      from_secret: gar_service_account_key
  when:
    event:
    - push
    branch:
    - main
    - dev
- name: Update GitOps Repo [Dev]
  image: dhawton/ktools:latest
  environment:
    SSH_KEY:
      from_secret: PIPELINE_SSH_KEY
    MANIFEST_HOST: github.com
    MANIFEST_USER: addysnip
    MANIFEST_REPO: gitops-app
    MANIFEST_BRANCH: main
    IMAGE: gcr.io/addysnip/addysnip/emailer
    IMAGE_TAG: ${DRONE_COMMIT_SHA:0:8}
    KUSTOMIZE_PATH: addysnip/overlays/dev
  when:
    event:
    - push
    branch:
    - dev
- name: Update GitOps Repo [Prod]
  image: dhawton/ktools:latest
  environment:
    SSH_KEY:
      from_secret: PIPELINE_SSH_KEY
    MANIFEST_HOST: github.com
    MANIFEST_USER: addysnip
    MANIFEST_REPO: gitops-app
    MANIFEST_BRANCH: main
    IMAGE: gcr.io/addysnip/addysnip/emailer
    IMAGE_TAG: ${DRONE_COMMIT_SHA:0:8}
    KUSTOMIZE_PATH: addysnip
  when:
    event:
    - push
    branch:
    - main
- name: Slack Webhook
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: drone-messages
    template: >
      {{#success build.status}}
        Success! Build #{{build.number}} for {{repo.name}}, event {{build.event}}, on {{build.branch}} succeeded. {{build.status}}
      {{else}}
        Uh-Oh! Build #{{build.number}} for {{repo.name}}, event {{build.event}}, on {{build.branch}} failed. <@everyone>
      {{/success}}
  when:
    status:
    - success
    - failure